dist: bionic
osx_image: xcode12.2
os:
  - linux
  - osx
language:
  - cpp
compiler:
  - gcc
addons:
  homebrew:
    packages: openssl
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - rpm
      - openssl
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
script:
  - gcc -v && g++ -v && cmake --version
  - make
  - make test
  - make package
  - make package_source
deploy:
  provider: releases
  token: "$GITHUB_API_KEY"
  file_glob: true
  file: 
   - "build/libict-*.tar.Z"
   - "build/libict-*.tar.gz"
   - "build/libict-*.sh"
   - "build/libict-*.deb"
   - "build/libict-*.rpm"
  on:
    tags: true
